//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gh61.WYSitor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gh61.WYSitor.Localization.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Form_Browse {
            get {
                return ResourceManager.GetString("Form_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Form_OK {
            get {
                return ResourceManager.GetString("Form_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageForm_DefaultAltText {
            get {
                return ResourceManager.GetString("ImageForm_DefaultAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make image physically smaller.
        /// </summary>
        public static string ImageForm_DoPhysicalResize {
            get {
                return ResourceManager.GetString("ImageForm_DoPhysicalResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file cannot be loaded.
        /// </summary>
        public static string ImageForm_ErrorImage {
            get {
                return ResourceManager.GetString("ImageForm_ErrorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        public static string ImageForm_Filter {
            get {
                return ResourceManager.GetString("ImageForm_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ImageForm_Height {
            get {
                return ResourceManager.GetString("ImageForm_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageForm_Path {
            get {
                return ResourceManager.GetString("ImageForm_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string ImageForm_Preview {
            get {
                return ResourceManager.GetString("ImageForm_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show real size.
        /// </summary>
        public static string ImageForm_ShowRealSize {
            get {
                return ResourceManager.GetString("ImageForm_ShowRealSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ImageForm_Size {
            get {
                return ResourceManager.GetString("ImageForm_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ImageForm_Title {
            get {
                return ResourceManager.GetString("ImageForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ImageForm_Width {
            get {
                return ResourceManager.GetString("ImageForm_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string LinkForm_Text {
            get {
                return ResourceManager.GetString("LinkForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string LinkForm_Url {
            get {
                return ResourceManager.GetString("LinkForm_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text align center.
        /// </summary>
        public static string Text_AlignCenter {
            get {
                return ResourceManager.GetString("Text_AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text align left.
        /// </summary>
        public static string Text_AlignLeft {
            get {
                return ResourceManager.GetString("Text_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text align right.
        /// </summary>
        public static string Text_AlignRight {
            get {
                return ResourceManager.GetString("Text_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string Text_BackgroundColor {
            get {
                return ResourceManager.GetString("Text_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Text_Bold {
            get {
                return ResourceManager.GetString("Text_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unordered list.
        /// </summary>
        public static string Text_BulletList {
            get {
                return ResourceManager.GetString("Text_BulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line highlight color.
        /// </summary>
        public static string Text_HighlightColor {
            get {
                return ResourceManager.GetString("Text_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HTML code.
        /// </summary>
        public static string Text_HtmlCode {
            get {
                return ResourceManager.GetString("Text_HtmlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        public static string Text_Image {
            get {
                return ResourceManager.GetString("Text_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigger indent.
        /// </summary>
        public static string Text_Indent {
            get {
                return ResourceManager.GetString("Text_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Text_Italic {
            get {
                return ResourceManager.GetString("Text_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert link.
        /// </summary>
        public static string Text_Link {
            get {
                return ResourceManager.GetString("Text_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered list.
        /// </summary>
        public static string Text_NumberedList {
            get {
                return ResourceManager.GetString("Text_NumberedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller indent.
        /// </summary>
        public static string Text_Outdent {
            get {
                return ResourceManager.GetString("Text_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string Text_TextColor {
            get {
                return ResourceManager.GetString("Text_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Text_Underline {
            get {
                return ResourceManager.GetString("Text_Underline", resourceCulture);
            }
        }
    }
}
